#css_dir = "$HOME/emptycss.css"
image_dir_enabled = true
image_dir = "$HOME/.markdown-preview-server/images"
template_dir = "$HOME/.dotfiles/markdown/templates"
template = "textbook"
feature_set = "all"
log_level = "info"
host = "127.0.0.1"
port = 8080
websocket_port = 8081
frontend_address = ""
#frontend_address = "http://localhost:5173"
