code --install-extension arcensoth.language-mcfunction
code --install-extension bradlc.vscode-tailwindcss
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension emcel.vscode-html-css
code --install-extension equinusocio.vsc-community-material-theme
code --install-extension esbenp.prettier-vscode
code --install-extension firefox-devtools.vscode-firefox-debug
code --install-extension graphql.vscode-graphql
code --install-extension hookyqr.jsdoctagcomplete
code --install-extension icrawl.discord-vscode
code --install-extension jackmacwindows.vscode-computercraft
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mongodb.mongodb-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension seatonjiang.gitmoji-vscode
code --install-extension serayuzgur.crates
code --install-extension sonarsource.sonarlint-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wakatime.vscode-wakatime